# Shell variables
# Generated by 'wal'
wallpaper='/home/jan/Pictures/wallpapers/test.jpg'

# Special
background='#03060C'
foreground='#c5cfd5'
cursor='#c5cfd5'

# Colors
color0='#03060C'
color1='#2F536A'
color2='#46676E'
color3='#61877A'
color4='#3F6680'
color5='#4F738A'
color6='#6D8EA0'
color7='#c5cfd5'
color8='#899095'
color9='#2F536A'
color10='#46676E'
color11='#61877A'
color12='#3F6680'
color13='#4F738A'
color14='#6D8EA0'
color15='#c5cfd5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
